version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: my-api-flask-backend
    ports:
      - "5252:5252"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: my-static-web-nginx-frontend
    ports:
      - "9000:9000"
