version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: my-static-web-nginx-frontend
    ports:
      - "9000:9000"
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: my-api-flask-backend
    ports:
      - "5252:5252"
    networks:
      - my-network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: my-nginx-proxy-server
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
